[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "@matterlabs/=lib/era-contracts/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"